name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --build-arg AUTH_CLIENT_ID="${{ secrets.AUTH_CLIENT_ID }}" \
            --build-arg AUTH_CLIENT_SECRET="${{ secrets.AUTH_CLIENT_SECRET }}" \
            --build-arg WARP_CONNECTOR_TOKEN="${{ secrets.WARP_CONNECTOR_TOKEN }}" \
            -t my_image \
            .
          docker push my_image
